Primer commit
agusbece/workshop-react pull request #1
Opened 2016-12-09 19:28 UTC by agusbece

@diegomura
Fijate que tal esta todo, si tenes alguna recomendacion. Parece ser bastante poco lo cambiado, pero he tenido que aprender bastante, y al empezar 1 semana despues del workshop tuve que refrescar bastante todo, je. 
La gui no es la mejor.

2016-12-09 20:46 UTC, diegomura requested changes
Esta muy bien!
Por mas que las features agregadas no fueron muchas, creo que entendiste bien la idea y para que sirve cada parte.

Podes responder los comentarios si tenes alguna duda, y cuando los resuelvas commitea para que lo vea (si queres) y despues mergear.

2016-12-09 20:46 UTC, diegomura commented on src/components/TimeEntry.js
> +//export default TimeEntry;
Eliminar esto

2016-12-09 20:46 UTC, diegomura commented on src/pages/Dashboard.js
> +  }
Este metodo no es necesario. Conviene pasarle al `onClick` directamente el metodo de `logOut` de las `props`

2016-12-09 20:46 UTC, diegomura commented on src/pages/Dashboard.scss
> +  button-logout {
Esto es el nombre de una clase. Le falta el punto (`.`) al principio

2016-12-09 20:46 UTC, diegomura commented on src/store/actions.js
> +  return { type: LOGOUT_SUCCESS, data: null /* ... */ }
Con `/* ... */` lo que queria decir es que aca podes poner cualquier tipo de informacion que sea necesaria para despues actualizar el estado. Si no necesitas nada (como en este caso), la action solo queda con la key `type` y listo.

Por otro lado, el motivo por el que tenemos `X_SUCCESS` y `X_FAILURE` es porque la llamada ajax puede fallar. En este caso donde no realizamos ningun request por la red, conviene simplemente llamar a la action `LOGOUT`

2016-12-10 00:06 UTC, agusbece commented on src/components/TimeEntry.js
> +//export default TimeEntry;
Asumi que debia conectarse al store, ya que en el TimeTracker tambien se hacia lo mismo

2016-12-10 00:19 UTC, agusbece commented on src/components/TimeEntry.js
> +//export default TimeEntry;
Creo, que se me rompio cuando lo saque... puede ser?

2016-12-10 16:27 UTC, diegomura requested changes
Creo que todavia no subiste los cambios. Avisame cuando lo hagas y los reviso.

Saludos!

2016-12-10 16:27 UTC, diegomura commented on src/components/TimeEntry.js
> +//export default TimeEntry;
Me referia a eliminar el comentario 😄

2016-12-10 16:27 UTC, diegomura commented on src/components/TimeEntry.js
> +    this.props.deleteTimeEntry(this.props.id);  }
Function mal indentada. El `}` tiene que ir debajo.

2016-12-10 16:27 UTC, diegomura commented on src/pages/Dashboard.js
> +  }
Ya esta hecho este cambio? No lo veo publicado

2016-12-11 13:25 UTC, agusbece commented on src/pages/Dashboard.js
> +  }
No pense que ibas a estar disponible el fin de semana, jeje. 
Ya arregle los comentarios, y tengo varios cambios. Ahora en un rato lo subo

2016-12-11 13:51 UTC, closed without merging