My work
agusbece/workshop-react pull request #4
Opened 2016-12-12 16:58 UTC by agusbece

2016-12-12 22:13 UTC, diegomura requested changes

2016-12-12 22:13 UTC, diegomura commented on src/components/TimeTracker.js
> +    console.log(moment().format());
eliminar `console.log`

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +    this.handleChangeTitleInput = ::this.handleChangeTitleInput;
para setear el estado inicial:

`this.state = { modalIsOpen: false }`

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +  getInitialState () {
Definir estado inicial en constructor

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +    this.setState({trackTitle: ''});
Se tiene que modificar el state en una simple llamada:

```js
this.setState({
  modalIsOpen: false,
  trackStartTime: '',
  trackEndTime: '',
  trackTitle: ''
});
```

Ademas, hay claves que no existen en el estado inicial. Hay que agregarlas

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +      this.setState({trackTitle: ''});
Lo mismo aca

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +    console.log(this.state.trackStartTime);
Eliminar `console.log`

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +    console.log(this.state.trackEndTime);
Eliminar `console.log`

2016-12-12 22:13 UTC, diegomura commented on src/pages/Dashboard.js
> +};
porque no hacer esto por CSS?

2016-12-12 22:16 UTC, diegomura requested changes

2016-12-12 22:16 UTC, diegomura commented on src/components/TimeEntry.js
> +    this.setState({trackTitle: this.props.title});
Chequear comentario en commit anterior

2016-12-13 01:55 UTC, agusbece commented on src/pages/Dashboard.js
> +    this.setState({trackTitle: ''});
Bien, no sabia que se podía hacer eso

2016-12-13 01:57 UTC, agusbece commented on src/pages/Dashboard.js
> +    this.handleChangeTitleInput = ::this.handleChangeTitleInput;
no entendi

2016-12-13 01:58 UTC, agusbece commented on src/pages/Dashboard.js
> +};
Lo saque de un ejemplo. Al no manejar bien el tema de CSS no estaba seguro de si se podía poner ahí o no.

2016-12-13 02:36 UTC, merged